### ISSUE TITLE
Reorganize tests to follow foundry best practices

### ISSUE THREAD

**Issue by alexkeating** [ScopeLift/optimizoors-perpetual-protocol#9]
- Naming and also making sure we target the appropriate test cases

**Comment by alexkeating** [comment]
https://github.com/ScopeLift/optimizoors-perpetual-protocol/pull/13#discussion_r1194043289 make sure to do inverse fuzz tests

**Comment by mds1** [comment]
@alexkeating looks like you opened a PR for this, so I'm going to reassign this issue to you
